### ISSUE TITLE
May commit did not trigger a website rebuild

### ISSUE THREAD

**Issue by jensh** [Schepp/wwnrw#8]
Irgendwas klemmt. bb82afff545ed0f43d253dbb56a7d4b6efc4097e ist auf http://webworker-nrw.de leider nicht zu sehen.

**Comment by Schepp** [comment]
Guter Hinweis, nicht bemerkt. Danke! Und nun deployed :)

Von: Jens Hauke [mailto:notifications@github.com]
Gesendet: Donnerstag, 18. Mai 2017 00:08
An: Schepp/wwnrw <wwnrw@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [Schepp/wwnrw] May commit did not trigger a website rebuild (#8)


Irgendwas klemmt. bb82aff<https://github.com/Schepp/wwnrw/commit/bb82afff545ed0f43d253dbb56a7d4b6efc4097e> ist auf http://webworker-nrw.de leider nicht zu sehen.
